eureka:
  client:
    registry-fetch-interval-seconds: 30
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
#指定具体服务的负载均衡策略
SEARCH: #编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #具体负载均衡的策略

#feign和Hystrix组件整合
feign:
  hystrix:
    enabled: true
