#指定Eureka服务地址
eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka,http://root:root@localhost:8762/eureka

version: v1
#指定服务的名称
spring:
  application:
    name: CUSTOMER-${version}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ems
    password: 123
    virtual-host: /ems
#指定具体服务的负载均衡策略
SEARCH: #编写服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #具体负载均衡的策略

#feign和Hystrix组件整合
feign:
  hystrix:
    enabled: true
